[atcoder]
submit_via_binary = false # submit via binary by default
use_cross = false         # use `cross` instead of `cargo` when generating binaries
binary_column = 80        # maximum column number of generated binary (0 for no wrapping)
update_interval = 1000    # interval time of fetching result (ms)
strip_path = "strip"      # specify `strip` command path. NOTE: if you use macOS, you have to install GNU strip and specify its path here.

[profile]
# target to use to generate binary
target = "x86_64-unknown-linux-musl"

[profile.release]
lto = true
panic = 'abort'

# dependencies added to new project
[dependencies]
# competitive = { git = "https://github.com/tanakh/competitive-rs.git" }
proconio = { version = "=0.3.6", features = ["derive"] }

[project]
# to create `rust-toolchain` file, uncomment this line.
# rustc_version = "1.15.1"

# source code template
template = """
use proconio::input;
fn main() {
    let solver = Solver::new();
    solver.solve();
}

struct Solver {}

impl Solver {
    fn new(s: String) -> Solver {
        Solver {}
    }

    fn solve(&self) {
        input! {}
        let ans = 0;
        println!("{}", ans);
    }
}
"""
