[package]
name = "abc171"
version = "0.1.0"
authors = ["canpok1 <6isstrong@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
